# HTTP Server配置   内网192.168.31.100配置文件
[server]
	Address         = ":7199"
	HTTPSAddr       = ""
	HTTPSCertPath   = ""
	HTTPSKeyPath    = ""
	ServerRoot     = "views"
	ServerAgent    = "gfWeb"
	NameToUriType  = 1          # 路由命名风格规则类型 0（默认)全部转为小写，单词以'-'连接符号连接; 1 不处理名称，以原有名称构建成URI; 2 仅转为小写，单词间不使用连接符号;3 采用驼峰命名方式
	RouteOverWrite = true       # 是否允许覆盖复制的路由
	ErrorStack        = true    # 错误时打印栈
	# 日志配置
	LogPath        = "logs/server"
	LogStdout       = true      # 日志控制台输出
	AccessLogEnabled = false     # http请求打印
    ErrorLogEnabled   = true
    ErrorLogPattern   = "error.{Ymd}.log"

    PProfEnabled     = true
	FileServerEnabled = true           # 静态文件服务总开关：是否开启/关闭静态文件服务
	IndexFolder     = false             # 是否允许展示访问目录的文件列表默认为false）

	SessionIdName   = "MySessionId"
    SessionPath     = "/tmp/MySessionStoragePath"
	SessionMaxAge   = "24h"
    DumpRouterMap   = false            # 是否打印路由内容
    Graceful        = true            # 热重启

	isAllowMultipleLogin = false        # 是否可多人登录

[compiler]
    name    = "admin"
    version = ""
    arch    = "amd64"
    system  = "linux"
    output  = ""
    path    = "E:/go/src/gfWeb"
    extra   = "-ldflags \"-s -w\""
# 全局日志配置
[logger]
    Dir    = "logs"
    Path   = "logs/gfWeb"
    Level  = "all"
    Stdout = true
    StStatus = 1        #是否开启堆栈打印

# 数据库连接
[database]
    sqlDownloadPath="/mysql_back"   # 数据库下载地址
    backDir="logs/mysql_back"      # 数据库打包、压缩目录(要先有这个目录，不然启动会报错)
# 后台数据库
[database.default]
    host         = "127.0.0.1"
    port         = "3306"
    user         = "root"
    pass         = "game1234"
    name         = "db_t3_admin"
    #name         = "admin"
    type         = "mysql"
    charset      = "utf8"
    debug        = "true"
    prefix      = "myadmin_"
# 中心服数据库
[database.center]
    host         = "127.0.0.1"
    port         = "3306"
    user         = "root"
    pass         = "game1234"
    name         = "db_t3_center"
    type         = "mysql"
    role         = "master"
    debug        = "true"
    weight       = "100"
    prefix       = ""
    charset      = "utf8"
    linkinfo     = ""
    maxIdle      = "10"         # 连接池最大闲置连接数
    maxOpen      = "100"        # 连接池最大打开连接数
    maxLifetime  = "30"
# 充值服(不配置读中心服配置)
[database.charge]
    name         = "db_t3_charge"
# 游戏服
[database.game]
    pass  = "game1234"
    visitor_pass  = "game1234"
# 数据库日志对象配置
[database.logger]
    Path   = "logs/sql"
    Level  = "all"
    Stdout = true
    ErrorLogEnabled  = true
    ErrorLogPattern   = "error.{Ymd}.log"

# 游戏配置
[game]
    platform_type = "local"
    cookie = "game"
    centerNode= "t3_center@192.168.31.100"  #
    # loginServerUrl = "http://192.168.31.100:16667/refresh" # ?? 没有服到 删除
    # 自动开服定时检测时间 秒
    checkOpenServerCronSecond = 0
    mailPrefixTitle = "【项目一】" # 邮件标题前面抬头

    log_dir = "/opt/t3/trunk/server/log/game/"
    script_path= "/opt/admin/t3/script/count_player_log.sh"
    script_path_monster= "/data/admin/script/count_monster_log.sh"
    ssh_key="/home/100"
    ssh_port =""
    #是否监控节点存活
    is_check_node=false
    # 游戏中机器的最低端口 默认10001
    game_min_port = 10000
    # 检测后台web活跃 平台,url  多个用"|"分隔
    check_back_web=""
    
    gs_domain = "http://127.0.0.1:6663"    # 是否与centerUrl一致 游戏中心服获取区服列表地址  
    equipTrade = "http://127.0.0.1:9993"  # 进行装备交易路径 
    gameCenterHost = "http://127.0.0.1:13000"  # 获取充值列表项，当充值到游戏钻石的时候 
    # gameCenterHostOnlyMonster = "http://127.0.0.1:13000"  #仅用于获取怪物json列表 
    env="develop"
# ansible工具
[ansible]
    # ansible工具路径
    tool_path = "/data/tool/ansible/"
    # ansible inventory 路径
    ansible_inventory_file="/etc/ansible/hosts"
    ansible_nodes_dir="/data/node_hosts/"

# 合服配置
[merge]
    # 合服时清理玩家
    cleanLevel=250      # 清理等级(小于等级)
    cleanVipLevel=0     # 清理vip(小于等级)
    cleanNoLoginDay=10  # 清理未登录天(小于)
    tableConfigPath="config/table_config.json"  # 合服关联表配置文件路径
    sqlOnceInsertMaxLimit=15000     # 数据库合服单次插入数据上限(不能太小，不然插入耗时;不能太大，不然会max_allowed_packet)
    mergeTablePageNum=3000000       # 合服单表数据分页值
[jiguang]
    url="https://api.jpush.cn/v3/push"
    gamename="賞金之刃"
    appKey="089a4e58e1b4e3ea59b326bd"   # 47c1e40cf85d9e675285f014
    masterSecret="964e8cdfb9b9603a35dabe8c" # 310cfd3132ddcf7fe4c48b4d
    